- name: Fetch rustup
  ansible.builtin.uri:
    url: https://sh.rustup.rs
    return_content: true
  register: rustup_installer

- name: Run rustup installer
  ansible.builtin.shell:
    cmd: sh -s -- -y
    stdin: "{{ rustup_installer.content }}"

# TODO : べき等性が保てていないのでどうにかしたい
# ref. https://ymotongpoo.hatenablog.com/entry/2021/03/01/224610
