---
- name: Fetch rustup
  uri:
    url: https://sh.rustup.rs
    return_content: yes
  register: rustup_installer

- name: Run rustup installer
  shell:
    cmd: sh -s -- -y
    stdin: "{{ rustup_installer.content }}"

# TODO : べき等性が保てていないのでどうにかしたい。

# ref. https://ymotongpoo.hatenablog.com/entry/2021/03/01/224610
