- name: Check if rustup is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
  register: rustup_bin

- name: Install Rust via rustup
  when: not rustup_bin.stat.exists
  block:
    - name: Fetch rustup installer
      ansible.builtin.uri:
        url: https://sh.rustup.rs
        return_content: true
      register: rustup_installer

    - name: Run rustup installer
      ansible.builtin.shell:
        cmd: sh -s -- -y
        stdin: "{{ rustup_installer.content }}"
