- when: IS_UBUNTU
  tags: shotcut
  block:
    - name: Install shotcut
      become: true
      community.general.snap:
        name: shotcut
        classic: true
        state: present

- when: IS_STEAMOS
  tags: shotcut
  block:
    - name: Install shotcut (flatpak)
      community.general.flatpak:
        name: org.shotcut.Shotcut
        state: present
        method: system
