- when: IS_UBUNTU
  tags: vlc
  block:
    - name: Install VLC
      become: true
      ansible.builtin.apt:
        name: vlc
        state: present

- when: IS_STEAMOS
  tags: vlc
  block:
    - name: Install VLC (flatpak)
      community.general.flatpak:
        name: org.videolan.VLC
        state: present
        method: system
