- name: Add apt key for GoogleChrome
  become: true
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: "{{ KEYRINGS_PATH }}/google.asc"

- name: Add specified repository into sources list
  become: true
  apt_repository:
    repo: 'deb [arch=amd64 signed-by={{ KEYRINGS_PATH }}/google.asc] https://dl.google.com/linux/chrome/deb/ stable main'
    filename: google-chrome
    state: present
    update_cache: yes

- name: Install GoogleChrome
  become: yes
  apt: name=google-chrome-stable state=present

# ref. https://www.google.com/linuxrepositories/
#      http://www.ubuntuupdates.org/ppa/google_chrome
