- when: IS_UBUNTU
  tags: googlechrome
  block:
    - name: Add apt key for GoogleChrome
      become: true
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: "{{ KEYRINGS_PATH }}/google.asc"

    - name: Add specified repository into sources list
      become: true
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by={{ KEYRINGS_PATH }}/google.asc] https://dl.google.com/linux/chrome/deb/ stable main'
        filename: google-chrome
        state: present
        update_cache: true

    - name: Install GoogleChrome
      become: true
      ansible.builtin.apt:
        name: google-chrome-stable
        state: present

- when: IS_STEAMOS
  tags: googlechrome
  block:
    - name: Install GoogleChrome (flatpak)
      community.general.flatpak:
        name: com.google.Chrome
        state: present
        method: system

# ref. https://www.google.com/linuxrepositories/
#      http://www.ubuntuupdates.org/ppa/google_chrome
