- name: Add apt key
  become: true
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa59e5ebfccc61564d6d4365b2763b0ee7709fe97
    dest: "{{ KEYRINGS_PATH }}/kdenlive.asc"

- name: Add specified repository into sources list
  become: true
  apt_repository:
    repo: "deb [signed-by={{ KEYRINGS_PATH }}/kdenlive.asc] https://ppa.launchpadcontent.net/kdenlive/kdenlive-stable/ubuntu {{ ansible_lsb.codename }} main"
    filename: kdenlive
    state: present
    update_cache: yes

- name: Add specified repository into sources list (src)
  become: true
  apt_repository:
    repo: "deb-src [signed-by={{ KEYRINGS_PATH }}/kdenlive.asc] https://ppa.launchpadcontent.net/kdenlive/kdenlive-stable/ubuntu {{ ansible_lsb.codename }} main"
    filename: kdenlive
    state: present
    update_cache: yes

- name: Install kdenlive
  become: yes
  apt:
    name: kdenlive
    state: present
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"
