- name: Adding this PPA to your system
  become: yes
  apt_repository:
    repo: 'ppa:kdenlive/kdenlive-stable'
    filename: kdenlive
    state: present
    update_cache: yes

- name: Install kdenlive
  become: yes
  apt:
    name: kdenlive
    state: present
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"
