- name: Install asciidoctor and asciidoctor-diagram
  become: true
  community.general.gem:
    name: "{{ item }}"
    user_install: false
    state: present
  loop:
    - asciidoctor-diagram
    - asciidoctor
