- name: Install direnv
  become: true
  ansible.builtin.apt:
    name: direnv
    state: latest
    update_cache: yes

- name: Setup
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      eval "$(direnv hook bash)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR DIRENV"

# ref. https://direnv.net/
