- name: Install direnv
  become: true
  tags: direnv
  ansible.builtin.apt:
    name: direnv
    state: latest
    update_cache: true

- name: Setup
  tags: direnv
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
    block: |
      eval "$(direnv hook bash)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR DIRENV"

# ref. https://direnv.net/
