- name: Install lxd
  become: true
  tags: lxd
  community.general.snap:
    name: lxd
    state: present

- name: Add lxd group
  become: true
  tags: lxd
  ansible.builtin.group:
    name: lxd
    state: present
  notify:
    - Restart lxd service

- name: Apply lxd group
  become: true
  tags: lxd
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: lxd
    append: true
    state: present
  notify:
    - Notify Re-login
