- name: Install
  become: yes
  snap:
    name: lxd
    state: present

- name: Add lxd group
  become: yes
  group:
    name: lxd
    state: present
  notify:
    - Restart lxd service

- name: Apply lxd group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: lxd
    append: yes
    state: present
  notify:
    - Notify Re-login
