- name: Install NodeJs
  block:
    - name: Add the NodeSource package signing key.
      become: true
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: "{{ KEYRINGS_PATH }}/nodesource.asc"
    - name: Add the desired NodeSource repository.
      become: yes
      apt_repository:
        repo: "deb [signed-by={{ KEYRINGS_PATH }}/nodesource.asc] https://deb.nodesource.com/node_{{ NODE_VER }} nodistro main"
        filename: nodesource
        state: present
        update_cache: yes
    - name: Add the desired NodeSource repository(src).
      become: yes
      apt_repository:
        repo: "deb-src [signed-by={{ KEYRINGS_PATH }}/nodesource.asc] https://deb.nodesource.com/node_{{ NODE_VER }} nodistro main"
        filename: nodesource
        state: present
        update_cache: yes
    - name: Install Node.js
      become: yes
      apt:
        name: nodejs
        state: present
        update_cache: yes

# https://github.com/nodesource/distributions#manual-installation

- name: Install Yarn
  block:
    - name: Add GPG key
      become: true
      ansible.builtin.get_url:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        dest: "{{ KEYRINGS_PATH }}/yarnpkg.asc"

    - name: You will first need to configure the repository
      become: yes
      apt_repository:
        repo: "deb [signed-by={{ KEYRINGS_PATH }}/yarnpkg.asc] https://dl.yarnpkg.com/debian/ stable main"
        filename: yarn
        state: present
        update_cache: yes

    - name: Install Yarn
      become: yes
      apt:
        name: yarn
        state: present
        update_cache: yes

# ref. https://yarnpkg.com/lang/en/docs/install/#debian-stable
