- name: Install Python3
  become: true
  tags: python
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: true

- name: Check if uv is installed
  tags: python
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/bin/uv"
  register: uv_bin

- name: Install uv
  tags: python
  when: not uv_bin.stat.exists
  block:
    - name: Fetch uv installer
      ansible.builtin.uri:
        url: https://astral.sh/uv/install.sh
        return_content: true
      register: uv_installer

    - name: Run uv installer
      ansible.builtin.shell:
        cmd: sh
        stdin: "{{ uv_installer.content }}"

# ref. https://docs.astral.sh/uv/
