- name: Install Python3
  become: yes
  apt:
    name: ["python3", "python3-pip"]
    state: present
    update_cache: yes

# 環境分離ツール(Python用)
- name: Install virtualenv
  become: yes
  apt:
    name: virtualenv
    state: present

- name: Install pyenv
  block:
    - name: Check out pyenv where you want it installed
      git:
        dest: "{{ ansible_env.HOME }}/.pyenv"
        repo: "https://github.com/pyenv/pyenv.git"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Define environment variable
      blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          if command -v pyenv 1>/dev/null 2>&1; then
            eval "$(pyenv init -)"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PYENV"
      notify:
        - Restart shell to activate pyenv

    - name: Install dependency packages
      become: yes
      apt:
        name: ["make", "build-essential", "libssl-dev", "zlib1g-dev", "libbz2-dev", "libreadline-dev", "libsqlite3-dev", "wget", "curl", "llvm", "libncurses5-dev", "xz-utils", "tk-dev", "libxml2-dev", "libxmlsec1-dev", "libffi-dev", "liblzma-dev"]
        state: present
        update_cache: yes

    # ref. https://github.com/pyenv/pyenv#installation
    # ref. https://github.com/pyenv/pyenv/wiki

- name: Install poetry
  become: yes
  apt:
    name: "python3-poetry"
    state: present
    update_cache: yes

