- name: Add apt key
  become: true
  ansible.builtin.get_url:
    url: https://mkvtoolnix.download/gpg-pub-moritzbunkus.txt
    dest: "{{ KEYRINGS_PATH }}/mkvtoolnix.asc"

- name: Add specified repository into sources list
  become: true
  apt_repository:
    repo: 'deb [arch=amd64 signed-by={{ KEYRINGS_PATH }}/mkvtoolnix.asc] https://mkvtoolnix.download/ubuntu/ {{ ansible_distribution_release }} main'
    filename: mkvtoolnix.download
    state: present
    update_cache: yes

- name: Add specified repository into sources list
  become: true
  apt_repository:
    repo: 'deb-src [arch=amd64 signed-by={{ KEYRINGS_PATH }}/mkvtoolnix.asc] https://mkvtoolnix.download/ubuntu/ {{ ansible_distribution_release }} main'
    filename: mkvtoolnix.download
    state: present
    update_cache: yes

- name: Install
  become: yes
  apt:
    name: ['mkvtoolnix', 'mkvtoolnix-gui']
    state: present
    update_cache: yes

# ref. https://mkvtoolnix.download/index.html
