- name: Add apt key
  become: true
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xbc7345f522079769f5bbe987efc71127f425e228
    dest: "{{ KEYRINGS_PATH }}/obsproject.asc"

- name: Add specified repository into sources list
  become: true
  apt_repository:
    repo: "deb [signed-by={{ KEYRINGS_PATH }}/obsproject.asc] https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu {{ ansible_lsb.codename }} main"
    filename: obsproject
    state: present
    update_cache: yes

- name: Add specified repository into sources list (src)
  become: true
  apt_repository:
    repo: "deb-src [signed-by={{ KEYRINGS_PATH }}/obsproject.asc] https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu {{ ansible_lsb.codename }} main"
    filename: obsproject
    state: present
    update_cache: yes

- name: Install OBS studio
  become: yes
  apt:
    name: obs-studio
    state: present
    update_cache: yes

- name: Install ndi plugin for OBS studio
  become: yes
  apt:
    deb: "{{ item }}"
    state: present
  loop:
    - https://github.com/Palakis/obs-ndi/releases/download/4.9.1/libndi4_4.5.1-1_amd64.deb
    - https://github.com/Palakis/obs-ndi/releases/download/4.9.1/obs-ndi_4.9.1-1_amd64.deb
  ignore_errors: "{{ ansible_check_mode }}"
