- name: Add apt key
  become: true
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE363C90F8F1B6217
    dest: "{{ KEYRINGS_PATH }}/git.asc"

- name: Add specified repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ KEYRINGS_PATH }}/git.asc] https://ppa.launchpadcontent.net/git-core/ppa/ubuntu {{ ansible_lsb.codename }} main"
    filename: git
    state: present
    update_cache: true

- name: Add specified repository into sources list (src)
  become: true
  ansible.builtin.apt_repository:
    repo: "deb-src [signed-by={{ KEYRINGS_PATH }}/git.asc] https://ppa.launchpadcontent.net/git-core/ppa/ubuntu {{ ansible_lsb.codename }} main"
    filename: git
    state: present
    update_cache: true

- name: Install git
  become: true
  ansible.builtin.apt:
    name:
      - git
      - git-svn
      - gitk
    state: latest
    update_cache: true

- name: bash completion support for core Git
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      if [ -f /usr/share/bash-completion/completions/git ]; then
        source /usr/share/bash-completion/completions/git
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR GIT-COMPLETION.BASH"

- name: Set git config
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - { name: 'alias.branches', value: 'branch -a' }
    - { name: 'alias.co', value: 'checkout' }
    - { name: 'alias.ci', value: 'commit -v' }
    - { name: 'alias.df', value: 'diff' }
    - { name: 'alias.dfcached', value: 'diff --cached' }
    - { name: 'alias.dfhead', value: 'diff HEAD' }
    - { name: 'alias.lg', value: 'log --graph --pretty=oneline --abbrev-commit --decorate=full' }
    - { name: 'alias.lgg', value: 'log --graph --pretty=short --abbrev-commit --decorate=full' }
    - { name: 'alias.lggg', value: 'log --graph --pretty=fuller --decorate=full' }
    - { name: 'alias.remotes', value: 'remote -v' }
    - { name: 'alias.s', value: 'status' }
    - { name: 'alias.stashes', value: 'stash list' }
    - { name: 'alias.dfls', value: 'diff --stat --name-only' }
    - { name: 'alias.sw', value: 'switch' }
    - { name: 'alias.rs', value: 'restore' }
    - { name: 'color.ui', value: 'true' }
    - { name: 'core.editor', value: 'vim' }
    - { name: 'core.pager', value: 'less -S -x4' }
    - { name: 'core.quotepath', value: 'false' }
    - { name: 'fetch.prune', value: 'true' }
    - { name: 'core.commentchar', value: ';' }
