- name: For Ubuntu, this PPA provides the latest stable upstream Git version
  become: yes
  apt_repository:
    repo: 'ppa:git-core/ppa'
    filename: git
    state: present
    update_cache: yes

# git がアップグレードされるのを許可
- name: Permit git from being upgraded.
  become: yes
  dpkg_selections:
    name: git
    selection: install
  changed_when: false

- name: Install git
  become: yes
  apt:
    name: "git=1:{{ GIT_VERSION }}-0ppa1~ubuntu{{ ansible_distribution_version }}.1"
    state: present
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"

# git がアップグレードされるのを禁止(prompt, completion の version とあわせるため)
- name: Prevent git from being upgraded.
  become: yes
  dpkg_selections:
    name: git
    selection: hold
  changed_when: false

- name: Install git-svn
  become: yes
  apt:
    name: git-svn
    state: present

- name: Install gitk
  become: yes
  apt:
    name: gitk
    state: present

- name: Download completion file for git
  get_url:
    url: "https://raw.githubusercontent.com/git/git/v{{ GIT_VERSION }}/contrib/completion/git-completion.bash"
    dest: "{{ ansible_env.HOME }}/.git-completion.bash"

- name: bash completion support for core Git
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      if [ -e "{{ ansible_env.HOME }}/.git-completion.bash" ]; then
        source {{ ansible_env.HOME }}/.git-completion.bash
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR GIT-COMPLETION.BASH"

# ref. アップグレードの抑止に関するメモ
#      https://github.com/ansible/ansible/issues/18889
#      https://manpages.debian.org/jessie/dpkg/dpkg.1.ja.html
