- name: Add apt key
  become: true
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xe1dd270288b4e6030699e45fa1715d88e1df1f24
    dest: "{{ KEYRINGS_PATH }}/git.asc"

- name: Add specified repository into sources list
  become: true
  apt_repository:
    repo: "deb [signed-by={{ KEYRINGS_PATH }}/git.asc] https://ppa.launchpadcontent.net/git-core/ppa/ubuntu {{ ansible_lsb.codename }} main"
    filename: git
    state: present
    update_cache: yes

- name: Add specified repository into sources list (src)
  become: true
  apt_repository:
    repo: "deb-src [signed-by={{ KEYRINGS_PATH }}/git.asc] https://ppa.launchpadcontent.net/git-core/ppa/ubuntu {{ ansible_lsb.codename }} main"
    filename: git
    state: present
    update_cache: yes

# git がアップグレードされるのを許可
- name: Permit git from being upgraded.
  become: yes
  dpkg_selections:
    name: git
    selection: install
  changed_when: false

- name: Install git
  become: yes
  apt:
    name: "git=1:{{ GIT_VERSION }}-0ppa1~ubuntu{{ ansible_distribution_version }}.1"
    state: present
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"

# git がアップグレードされるのを禁止(prompt, completion の version とあわせるため)
- name: Prevent git from being upgraded.
  become: yes
  dpkg_selections:
    name: git
    selection: hold
  changed_when: false

- name: Install git-svn
  become: yes
  apt:
    name: git-svn
    state: present

- name: Install gitk
  become: yes
  apt:
    name: gitk
    state: present

- name: Download completion file for git
  get_url:
    url: "https://raw.githubusercontent.com/git/git/v{{ GIT_VERSION }}/contrib/completion/git-completion.bash"
    dest: "{{ ansible_env.HOME }}/.git-completion.bash"

- name: bash completion support for core Git
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      if [ -e "{{ ansible_env.HOME }}/.git-completion.bash" ]; then
        source {{ ansible_env.HOME }}/.git-completion.bash
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR GIT-COMPLETION.BASH"

# ref. アップグレードの抑止に関するメモ
#      https://github.com/ansible/ansible/issues/18889
#      https://manpages.debian.org/jessie/dpkg/dpkg.1.ja.html

- name: Set git config
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: 'alias.branches', value: 'branch -a'}
    - { name: 'alias.co', value: 'checkout'}
    - { name: 'alias.ci', value: 'commit -v'}
    - { name: 'alias.df', value: 'diff'}
    - { name: 'alias.dfcached', value: 'diff --cached'}
    - { name: 'alias.dfhead', value: 'diff HEAD'}
    - { name: 'alias.lg', value: 'log --graph --pretty=oneline --abbrev-commit --decorate=full'}
    - { name: 'alias.lgg', value: 'log --graph --pretty=short --abbrev-commit --decorate=full'}
    - { name: 'alias.lggg', value: 'log --graph --pretty=fuller --decorate=full'}
    - { name: 'alias.remotes', value: 'remote -v'}
    - { name: 'alias.s', value: 'status'}
    - { name: 'alias.stashes', value: 'stash list'}
    - { name: 'alias.dfls', value: 'diff --stat --name-only'}
    - { name: 'color.ui', value: 'true'}
    - { name: 'core.editor', value: 'vim'}
    - { name: 'core.pager', value: 'less -S -x4'}
    - { name: 'core.quotepath', value: 'false'}
    - { name: 'fetch.prune', value: 'true'}
