- name: Add HashiCorp GPG key
  become: true
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: "{{ KEYRINGS_PATH }}/hashicorp.asc"

- name: Add HashiCorp repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ KEYRINGS_PATH }}/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
    filename: hashicorp
    state: present
    update_cache: yes

- name: Install Terraform
  become: yes
  ansible.builtin.apt:
    name: terraform
    state: latest

# ref. https://developer.hashicorp.com/terraform/install
