- name: Install dependent packages
  become: yes
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes

- name: Add GPG key.
  become: true
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: "{{ KEYRINGS_PATH }}/microsoft.asc"

- name: Use the following command to set up the stable repository.
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by={{ KEYRINGS_PATH }}/microsoft.asc] https://packages.microsoft.com/repos/vscode stable main"
    filename: vscode
    state: present
    update_cache: yes

- name: Install
  become: yes
  apt:
    name: code
    state: latest
    update_cache: yes

# https://code.visualstudio.com/docs/setup/linux
