- when: IS_UBUNTU
  tags: soundconverter
  block:
    - name: Install soundconverter
      become: true
      ansible.builtin.apt:
        name: soundconverter
        state: present
        update_cache: true

- when: IS_STEAMOS
  tags: soundconverter
  block:
    - name: Install soundconverter (flatpak)
      community.general.flatpak:
        name: org.soundconverter.SoundConverter
        state: present
        method: system
