- when: IS_UBUNTU
  tags: meld
  block:
    - name: Install meld
      become: true
      ansible.builtin.apt:
        name: meld
        state: present

- when: IS_STEAMOS
  tags: meld
  block:
    - name: Install meld (flatpak)
      community.general.flatpak:
        name: org.gnome.meld
        state: present
        method: system
