- name: Install PHP
  become: true
  ansible.builtin.apt:
    name:
      - php
      - php-xml
      - php-sqlite3
      - php-mysql
      - php-pgsql
      - composer
    state: present
    update_cache: true

- name: Install php-cs-fixer
  become: true
  ansible.builtin.get_url:
    url: "https://cs.symfony.com/download/php-cs-fixer-v2.phar"
    dest: "/usr/local/bin/php-cs-fixer"
    mode: "+x"
    validate_certs: false

# ref. https://the2g.com/post/visual-studio-code-php-formatter
