- name: Remove vim-tiny
  become: true
  tags: vim
  ansible.builtin.apt:
    name: vim-tiny
    state: absent

- name: Install vim
  become: true
  tags: vim
  ansible.builtin.apt:
    name: vim
    state: present

- name: Copy vimrc
  tags: vim
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ ansible_facts['env']['HOME'] }}/.vimrc"
    backup: true
  notify:
    - Warning for vim
