- name: Remove vim-tiny
  become: yes
  apt: name=vim-tiny state=absent
- name: Install vim
  become: yes
  apt: name=vim state=present
- name: Copy vimrc
  copy: src=vimrc dest={{ ansible_env.HOME }}/.vimrc backup=yes
  notify:
    - Warning for vim
