- name: Install pandoc
  become: true
  tags: pandoc
  ansible.builtin.apt:
    name: pandoc
    state: latest

- name: Install WeasyPrint
  become: true
  tags: pandoc
  ansible.builtin.apt:
    name: weasyprint
    state: present

# ref. https://weasyprint.org/start/
