- name: Install pandoc
  become: true
  ansible.builtin.apt:
    name: pandoc
    state: latest

- name: Install PDF conversion packages
  become: true
  ansible.builtin.apt:
    name:
      - texlive-xetex
      - texlive-latex-recommended
      - texlive-lang-japanese
      - fonts-noto-cjk
    state: present
