- name: Add apt key for PostgreSQL
  become: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add specified repository into sources list
  become: yes
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main'
    filename: pgdg
    state: present
    update_cache: yes

- name: Install postgresql-client
  become: yes
  apt:
    name: postgresql-client-{{ POSTGRESQL_CLIENT_VER }}
    state: present

# ref. https://www.postgresql.org/download/linux/ubuntu/
