- name: Add apt key for PostgreSQL
  become: true
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: "{{ KEYRINGS_PATH }}/postgresql.asc"

- name: Add specified repository into sources list
  become: true
  apt_repository:
    repo: 'deb [arch=amd64 signed-by={{ KEYRINGS_PATH }}/postgresql.asc] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main'
    filename: pgdg
    state: present
    update_cache: yes

- name: Install postgresql-client
  become: yes
  apt:
    name: postgresql-client-{{ POSTGRESQL_CLIENT_VER }}
    state: present

# ref. https://www.postgresql.org/download/linux/ubuntu/
